<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPJCoa4h\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPJCoa4h/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPJCoa4h.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPJCoa4h\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPJCoa4h\App_KernelDevDebugContainer([
    'container.build_hash' => 'PJCoa4h',
    'container.build_id' => '368f2ab0',
    'container.build_time' => 1727218942,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPJCoa4h');
